name: cmdataaction2 CI Sequential
on:
 push:
   branches: [ main ]
     
jobs:
  hello1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: say hello
        run: echo "Hello from $GITHUB_WORKFLOW on commit $GITHUB_SHA"

  hello2:
    runs-on: ubuntu-latest
    needs: hello1
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Job 2"

  hello3:
    runs-on: ubuntu-latest
    needs: hello2
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Job 3"
    