name: Conditional Hello CI

on:
  push:
    branches:
      - '**'

jobs:
  always-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This always runs"

  only-on-main:
    runs-on: ubuntu-latest
    #only run this job if the current branch is main
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "This runs only on the main branch"
